### ISSUE TITLE
license as MIT?

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GRIBDatasets.jl#15]
Hi there, I'm just going through all the JuliaGeo license files to standardize the formats, and I noticed this repository is the only non-MIT repository in all of JuliaGeo.

Of course Apache-2.0 is also a well known permissive license, but for consistency I was wondering if there is a reason to deviate here? If you wish to also license it as Apache-2.0, perhaps it can be dual licensed under Apache-2.0 and MIT as is common in the Rust community?

**Comment by tcarion** [comment]
Hi!
The reason behind the Apache-2.0 license is that GRIBDatasets originally took some code from the old [CfGRIB](https://github.com/ecmwf/cfgrib.jl) package, which was Apache. Since I'm unfamiliar with how licenses work, I thought I had to take the same one. What does it imply to change the license? Can I just change it right away?

**Comment by visr** [comment]
I see, thanks. Since you are the only contributor right now, you can just change the license yourself. I see you already link to cfgrib.jl in the readme and mention you adapted the code, that's always a good idea to give credit. The licenses are so similar that in practice I don't really think there's much of an issue. If the source would be GPL it would.

If you prefer to stick to the Apache license it's also fine by me, then we can just close this issue.

**Comment by tcarion** [comment]
Alright, thanks, I agree with changing the license for consistency!
